### PR TITLE
Update version and classifiers to include tested python versions

### PR DESCRIPTION
**Pull request by neilmb**
This is just a version bump for a new PyPI release and to advertise the compatibility with Python 3.

### CODE REVIEW

**Comment by neilmb** [comment]
@b4hand The `setup.py` references the email address `dan@moz.com` which may not go anywhere anymore. Should we change that to point to something else?

**Comment by dlecocq** [comment]
Indeed, `dan@moz.com` certainly no longer goes to me :-) I imagine it's also still lingering around in a number of other `setup.py` files. I think `github` has a notion of a public email alias for a given user? I'll look into that, because that is probably the best way forward.

**Comment by dlecocq** [comment]
Supposedly `952157+dlecocq@users.noreply.github.com` is supposed to _just work_, but so far I've been unable to get anything sent to that email address, so that may not be a viable option.

**Comment by b4hand** [comment]
I think the `noreply` email address is exactly that. Not usable for replies. :)

**Comment by dlecocq** [comment]
I had suspected that, but for some reason I was under the impression that it was usable.

**Comment by dlecocq** [comment]
Maybe instead of an author name, could just be a github username URL? And then just drop the email altogether?

**Comment by b4hand** [comment]
https://help.github.com/articles/about-commit-email-addresses/

**Comment by b4hand** [comment]
I think it's a pretty limited value. In general, GitHub issues would be preferred for contact since that doesn't contact just a single individual, but I also don't think it hurts anything if dlecocq really wants an email address there either. FWIW, according to the link above, using a URL in the email field would be frowned upon, but you can provide additional "address" information in the author field.

**Comment by neilmb** [comment]
I'm going to put Dan's github user page in the `author` field and remove `author_email`.

**Comment by neilmb** [comment]
@b4hand You might want to hold off on a 0.6.0 release until I fix issue 38.

**Pull request merged**
